
plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.142'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}
version = mod_version

group = 'net.abraxator'

base {
    archivesName.set("MoreSnifferFlowers-${minecraft_version}-Forge")
}

repositories {
    mavenLocal()
    exclusiveContent {
        forRepository {
            maven {
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven { url = "https://maven.blamejared.com/" }
    maven { url = "https://modmaven.dev" }
    maven {
        name = 'Shedaniel\'s Maven' //REI
        url ="https://maven.shedaniel.me"
    }
    maven {
        name = "TerraformersMC" //EMI
        url = "https://maven.terraformersmc.com/"
    }
    flatDir { dir 'libs' }


    maven {
        url = 'https://nikdo53.github.io'
    }
}


java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"


    legacyForge {
        version = project.minecraft_version+'-'+forge_version

        parchment {
            mappingsVersion = project.parchment_mappings_version
            minecraftVersion = project.minecraft_version
        }

        runs {
            configureEach {
                gameDirectory = layout.projectDir.dir("runs/$name")
                systemProperty 'forge.logging.console.level', 'debug'
                systemProperty 'forge.logging.markers', 'REGISTRIES'

            }
            client {
                client()
            }
            clientAuth {
                client()
                devLogin = true
                gameDirectory = layout.projectDir.dir("runs/client")
            }
            data {
                data()
                programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            }
            server {
                server()
                programArgument('--nogui')
            }
        }
        mods {
            more_sniffer_flowers {
                sourceSet(sourceSets.main)
            }
        }
    }

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation 'org.jetbrains:annotations:26.0.1'

    //jei
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
   // modRuntimeOnly("curse.maven:jei-238222:6075247")

    //mixin
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:[0.5.4,)"))
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.4"))

    jarJar(modImplementation("net.nikdo53:tiny-multiblock-lib-forge-1.20.1:${tiny_multiblock_lib_version}"))
    implementation("net.nikdo53:nikdo-color:1.0.0")

    //quark
    compileOnly("curse.maven:quark-243121:6427817")
    compileOnly("curse.maven:zeta-968868:6432578")

    //farmersDelight
    modRuntimeOnly("curse.maven:farmers-delight-398521:8672742");
    modCompileOnly("curse.maven:farmers-delight-398521:8672742");

    // modImplementation("maven.modrinth:dye-depot:1.2.1-forge")
    // modImplementation("curse.maven:worldedit-225608:4586218")
}

mixin {
    add sourceSets.main, "${mod_id}.mixins.refmap.json"
    config "${mod_id}.mixins.json"
}

jar {
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
    finalizedBy('reobfJar')
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version        : minecraft_version,
            forge_version            : forge_version,
            mod_id                   : mod_id,
            mod_name                 : mod_name,
            mod_license              : "MIT",
            mod_version              : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

publishMods {
    file = reobfJar.archiveFile
    modLoaders.add("forge")
    modLoaders.add("neoforge")

    displayName = "$mod_name $mod_version - $minecraft_version Forge"

    type = STABLE
    changelog = rootProject.file("CHANGELOG.md").text

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "884119"
        minecraftVersions.add(minecraft_version)
        clientRequired = true
        serverRequired = true
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "DbriYWc8"
        minecraftVersions.add(minecraft_version)
    }
}

publishing {
    repositories {
        maven {
            url = "$rootDir/build/maven"
        }
    }
    publications {
        gpr(MavenPublication) {
            from(components.java)
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}