org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_id=moresnifferflowers

minecraft_version=1.21.1
neoforge_version=21.1.200
neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

jei_version=19.21.0.247
rei_version=15.0.728
emi_version=1.1.5

version=6.0