modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Nikdo53/MoreSnifferFlowers/issues"

[[mods]]
modId="moresnifferflowers"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="moresnifferflowers:dyespria"
logoFile= "moresnifferflowers_logo.png"
authors="AbraXator, Nikdo53"
description="Minecraft mod expanding upon the sniffer, adding entire new mechanics, while keeping it somewhat vanilla friendly"

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.moresnifferflowers]]
    modId="forge"
    mandatory = true
    versionRange="[47.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moresnifferflowers]]
    modId="minecraft"
    mandatory = true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.moresnifferflowers]]
    modId="tinymultiblocklib"
    mandatory = true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"

